version: '3.8'

networks:
  cicd:

services:
  dind:
    image: docker:dind
    container_name: docker
    privileged: true
    restart: unless-stopped
    networks:
      cicd:
    ports:
      - 2376:2376
    tty: true
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    restart: unless-stopped
    image: somikhaylov/jenkins:lts-jdk11-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    networks:
      cicd:
    user: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_casc.yaml:/var/jenkins_casc.yaml
      - ./certs:/certs/client
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
